### ISSUE TITLE
[소스코드] main 함수 한 곳으로 모으기

### ISSUE THREAD

**Issue by han222** [CindyYoon/StudentInformationSystem#4]
각 java 파일에서 main 함수 한 java 파일로 모으기
main 함수가 하나가 되도록!!

**Comment by CindyYoon** [comment]
내가 src/main/에 Main.java 만들어서 만들어서push했어! fetch바람~~~
Add 기능 부분도 완료!

**Comment by han222** [comment]
update 기능 부분 main.java로 뺏음~!!

**Comment by han222** [comment]
모든 기능 main.java에 모으기 완료~!!
