### ISSUE TITLE
[Add_student.java] 정보 추가 완료시 메시지 띄우는 부분

### ISSUE THREAD

**Issue by han222** [CindyYoon/StudentInformationSystem#5]
Add_student.java 파일 31~39번째 줄에

if (occur_duplecation == 1) {
    System.out.println("-> 이미 추가된 학번입니다.");
    System.out.println("-> 다시 작성해 주세요.\n");
} else if (occur_duplecation == 0) {
    // 저장 함수 호출
    addStudentToDatabase(input_id, input_name, input_depart, input_phonenumber);
    System.out.println("-> 성공적으로 학생정보가 추가되었습니다.\n");
    break;
}

요렇게 되어 있는데 update부분 수정하면서 해보니까
이렇게하면 오류나도 성공했다는 메시지가 무조건 뜸!!

---

=> DatabaseQuery.java 파일 37, 41번째 출처럼

public static void Database_Updatestudent(int id, String phone)
{
    try
    {
        DatabaseConnect.Database_connect();
        DatabaseConnect.stmt = DatabaseConnect.conn.prepareStatement("UPDATE swe2015.student SET phone_number='"+phone+"' WHERE ID='"+id+"'");
        DatabaseConnect.stmt.executeUpdate();
        DatabaseConnect.stmt.close();
        DatabaseConnect.Database_disconnect();
        System.out.println("-> 성공적으로 학생정보가 수정되었습니다.\n");   //★요기!!
    }
    catch (SQLException e)
    {
        System.out.println("-> 학생정보 수정에 실패했습니다.\n");    //★요기!
        e.printStackTrace();
    }
}

요렇게 디비 쿼리문 쪽에 메시지를 넣어야 제대로 뜸!!
확인해보고 수정 바람~ @.@

**Comment by CindyYoon** [comment]
해결했어~~push했으니까 확인할 수 있을거양!

**Comment by CindyYoon** [comment]
해결했어~~push했으니까 확인할 수 있을거양!

**Comment by CindyYoon** [comment]
해결했어~~push했으니까 확인할 수 있을거양!
